name: Fetch Arxiv Papers

on:
  schedule:
    - cron: "0 1 * * *"  # Cronjob schedule to run at 9 PM ET (01:00 UTC)
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  fetch_arxiv:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install arxiv package
      run: pip install arxiv sentence-transformers scikit-learn groq openai

    - name: Fetch Arxiv papers
      env:
        GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        # OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        python fetch_arxiv.py

    - name: Commit and push results
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add assets/json/arxiv_papers.json
        git add assets/json/arxiv_papers_*.json
        git add assets/json/summary.json
        git commit -m "Update arxiv_papers.json and summary.json with today's papers"
        git push

